### ISSUE TITLE
2.x Todo

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Intl#21]
Hi @pmjones ,

It looks to me the todo is already done https://github.com/auraphp/Aura.Intl/blob/2.x/TODO.md .

Can you make sure if there is anything that need to be done ?

**Comment by harikt** [comment]
Hi Paul, 

I have made the necessary changes removing the dependencies on aura/installer-default , the auto wiring of di container test, moved to psr-4 and docs to docs folder.

The licence has been changed from BSD to MIT as in v3 repo of Payload.

No api is changed and is all compatible so far .

Thank you

**Comment by frederikbosch** [comment]
@harikt @pmjones Any news on a release? Do you need any help? I'd like to contribute where needed.

**Comment by frederikbosch** [comment]
Or maybe a beta/alpha release?

**Comment by harikt** [comment]
@frederikbosch Thank you for the ping.

Current Aura.Intl 2.x branch is just removing a few unwanted composer dependency. Apart from that there is not much changes.

So I am not sure whether we need a beta or alpha itself ;-) .

Probably @pmjones may be able to share more information on this.

Thank you.

**Comment by frederikbosch** [comment]
Bump :)

**Comment by jhuet** [comment]
Hi there, also wondering if there is anything keeping from tagging the 2.x branch final ?

**Comment by harikt** [comment]
I am closing this for it looks most of the things are done.

Onething that seems missing is 

> More specific exception classes

May be we can revisit this later ;-) .

Other issues are 

~~README examples for fallbacks~~

~~README examples for all-at-once configuration~~

~~Rename "Catalog" to "Package"~~

~~Rename "Package" to "PackageLocator"~~

~~Create a Package description object that has properties for messages, formatter, and fallback~~

~~Create a PackageFactory~~

seems to me has already addressed.

@pmjones feel free to re-open the issue in case you think I missed something here.

Thank you
