### ISSUE TITLE
2.x release

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Intl#33]
Hi @pmjones ,

I would like to hear how you would love to release Aura.Intl. Can we push a 2.x release or do you think it is going for 3.x release ?

May be we need a few betas or can we push this to a stable x.0.0 on the fly for there is little changes.

I will be happy to do the releases if you raise the green flag :) .

Thank you.

**Comment by pmjones** [comment]
All of the 2.x packages are 5.3 compatible, which apparently this is not ... ?

**Comment by harikt** [comment]
@pmjones you are correct. This is 5.5 + . We tried to resolve the bug as reported in https://github.com/auraphp/Aura.Intl/issues/6 .

**Comment by pmjones** [comment]
Weird as it may seem, then, I think the thing to do is go straight to 3.x.

**Comment by harikt** [comment]
@pmjones as each package is self contained I think versions don't matter. So I am good with 2.x though.

**Comment by pmjones** [comment]
The problem is that that rules for 2.x state that it's 5.3 compatible. The 3.x rules allow for 5.5.

**Comment by harikt** [comment]
ok. 3.x then. Start with beta right ? I would love if you could do a review and release. If not I can do the same.

Thank you.

**Comment by pmjones** [comment]
Yeah, start with a beta.

Do you want to try something new? Let's try using CHANGELOG.md instead of CHANGES.md. That would make it pds/skeleton compliant. (Probably requires a change to the Aura release3 binary.)

However, if you do not want to try something new, that is totally fine with me. :-)

**Comment by harikt** [comment]
> Yeah, start with a beta.

sure.

> Do you want to try something new? Let's try using CHANGELOG.md instead of CHANGES.md. That would make it pds/skeleton compliant. (Probably requires a change to the Aura release3 binary.)

Could you look into https://github.com/auraphp/bin/pull/8 and merge if that is ok with you.

In that case we can make things possible to CHANGELOG.md file.

**Comment by harikt** [comment]
3.0.0-beta1 Released : https://github.com/auraphp/Aura.Intl/releases/tag/3.0.0-beta1

**Comment by ADmad** [comment]
Guys is there a roadmap for 3.0?  Is the version bump primarily due to PHP version bump and directory structure changes or backwards incompatible changes to public API are also planned? 

We want to use Aura.Intl 3.0 for next minor release 3.4 of CakePHP so knowing about potential breaking changes is important.

**Comment by harikt** [comment]
Hi @ADmad ,

Nice to see you here. 

> Guys is there a roadmap for 3.0?

Sorry currently there is no roadmap. But I would love to release a stable 3.0 as soon as possible.

> Is the version bump primarily due to PHP version bump and directory structure changes or backwards incompatible changes to public API are also planned?

As I mentioned in https://groups.google.com/d/msg/auraphp/GdZlkaCzeZo/rsPAiYT0EQAJ there is no BC break for public API. 

A few reasons we did released 3.0 is to remove the aura/installer-default and di wiring tests. See https://github.com/auraphp/Aura.Intl/issues/17

> We want to use Aura.Intl 3.0 for next minor release 3.4 of CakePHP so knowing about potential breaking changes is important.

@lorenzo already tested this. See https://github.com/auraphp/Aura.Intl/pull/29#issuecomment-255680147 .

I would love to know if the release notes need more update to make things clearer. https://github.com/auraphp/Aura.Intl/releases/tag/3.0.0-beta1 .

Let me know so we can address the same.

Thank you

**Comment by ADmad** [comment]
> If you are using the component as standalone and your PHP version is 5.6+ you are all good for a go. **There is no other BC breaks**.

This is what I wanted to know, thanks.

> lorenzo already tested this. See #29 (comment) .

I wasn't aware of that.

>  I would love to know if the release notes need more update to make things clearer. https://github.com/auraphp/Aura.Intl/releases/tag/3.0.0-beta1

I did check the release statement, but it didn't answer my concern :)  So adding "There is no other BC breaks"  or something to that effect would be nice.
