### ISSUE TITLE
Undocumented Features (factories and fallbacks)

### ISSUE THREAD

**Issue by jakejohns** [auraphp/Aura.Intl#35]
There's a few things I'm not seeing any documentation for:
- PackageFactory
- fallback translators

Am I just missing it?

**Comment by harikt** [comment]
You are right, they are not documented.

**Comment by q2dg** [comment]
Well, in fact this project seems abandonated...

**Comment by harikt** [comment]
Hi @q2dg ,

There is no open bugs, documentation for PackageFactory etc may be missing.

You can look at the stats :  https://packagist.org/packages/aura/intl/stats

The major player using Aura.Intl is @cakephp . And if no one is maintaining we will be more happy for cakephp taking the project.

Or if anyone is interested writing documentation send a Pull request and ping me. I will look and merge.

Thank you.
