### ISSUE TITLE
Not installable with PHP8

### ISSUE THREAD

**Issue by tylerlazenby** [auraphp/Aura.Intl#37]
This package is not compatible with PHP8 because your composer package is limiting against it.

**Comment by ajaykalashikaraoh** [comment]
Any alternative or fix for this? It is a required package for cake-up 4 and I am not able to install it with PHP 8.0 and cakephp won't install without it. Any insight greatly appreciated.

Thanks in advance

**Comment by harikt** [comment]
Does https://github.com/auraphp/Aura.Intl/pull/36 fixes the issue ?

**Comment by harikt** [comment]
Closing for 3.0.1 will support from 5.6 to 8.1 and has been released.
