### ISSUE TITLE
Select format isn't supported by IntlFormatter

### ISSUE THREAD

**Issue by samdark** [auraphp/Aura.Intl#6]
``` php
$formatter = new \Aura\Intl\IntlFormatter();
$pattern = '{name} is {gender} and {gender, select, female{she} male{he} other{it}} report bugs!';
echo $formatter->format('en_US', $pattern, array(
    'name' => 'Alexander',
    'gender' => 'male',
));
```

Should produce `Alexander is male and he report bugs!` but instead gives `Alexander is male and 3 report bugs!`. PHP 5.5's `MessageFormatter` does it properly.

**Comment by harikt** [comment]
Hey @samdark ,

nice to see you here. And Thank you for playing around with Aura and for the bug.

For the current time, you can resolve this by one of the means 

``` php
<?php
require __DIR__  . '/vendor/autoload.php';
$formatter = new \Aura\Intl\IntlFormatter();

// 1st way
$pattern = '{gender, select, female{{name} is {gender} and she report bugs!} male{{name} is {gender} and he report bugs!} other{{name} is {gender} and it report bugs!}}';

echo $formatter->format('en_US', $pattern, array(
    'name' => 'Alexander',
    'gender' => 'male',
));

// 2nd way
$pattern = "{gender, select,
    female {
        {count, plural, offset:1        
            other {{name} is {gender} and she report bugs!}
        }
    }
    male {
        {count, plural, offset:1
    other {{name} is {gender} and he report bugs!}
        }
    }
    other {
        {count, plural, offset:1
            other {{name} is {gender} and it report bugs!}
        }
    }
}";
echo $formatter->format('en_US', $pattern, array(
    'name' => 'Alexander',
    'gender' => 'male',
    'count' => ''
));
```

We have taken some of the tests from the source of php. You can see at https://github.com/auraphp/Aura.Intl/blob/develop/tests/Aura/Intl/IntlFormatterTest.php#L64

One of the problem I am seeing is getting rid of the patterns like 

``` php
msgfmt_format_message(
  'en_US', '
  {0, select, somevalue{This is some value} other{Unknown value}}', 
  ['somevalue']
);
```

@pmjones is on travel, once he is back. You may get more details.

**Comment by harikt** [comment]
one more information

``` php
<?php
$msg = '{0 is 1 and 1, select, female{she} male{he} other{it} report bugs!}';
echo PHP_EOL . msgfmt_format_message(
    'en_US',
    $msg,
    [
      'Alexander',
      'male'
    ]
);

$msg = '{0, select, female{she report bugs!} male{he report bugs!} other{it report bugs!}}';
echo PHP_EOL . msgfmt_format_message(
    'en_US',
    $msg,
    [      
      'male'
    ]
);

$msg = '{0, select, female{{1} is {0} and she report bugs!} male{{1} is {0} and he report bugs!} other{{1} is {0} it report bugs!}}';
echo PHP_EOL . msgfmt_format_message(
    'en_US',
    $msg,
    [      
      'male',
      'Alexander',
    ]
);
```

Try those, you can see the first one ends up in error.
It seems like the format is wrong ?

And also the format 

``` php
$pattern = '{gender, select, female{{name} is {gender} and she report bugs!} male{{name} is {gender} and he report bugs!} other{{name} is {gender} and it report bugs!}}';

echo $formatter->format('en_US', $pattern, array(
    'name' => 'Alexander',
    'gender' => 'male',
));
```

gives you the desired output.

See issue #7 with the test.

**Comment by harikt** [comment]
@samdark further I think your desired format will not work, else you can open with another test case showing the msg_formatter

``` php
$msg = '{0 is 1 and 1, select, female{she} male{he} other{it} report bugs!}';
echo PHP_EOL . msgfmt_format_message(
    'en_US',
    $msg,
    [
      'Alexander',
      'male'
    ]
);
```

**Comment by harikt** [comment]
About your issue with 5.4 and 5.5 , probably the version compatibility itself with PHP .

**Comment by samdark** [comment]
@harikt the format I've provided originally is valid for ICU and works just fine in PHP 5.5 but fails in 5.3 and 5.4. In 5.5 there were 2 bugs fixed in intl:
1. Ability to use named parameters (that's why I guess Aura has the wrapper around it).
2. Ability not to pass all token values.

So overall, yeah, one can just avoid using certain formats but since docs are ICU's and it's valid I don't think it's the right way.

I'm currently trying to create a wrapper for `MessageFormatter` for Yii that solves these two issues by replacing named parameters with positional ones and adding dummy values for parameters where data wasn't provided and stucked with alike problem.

**Comment by harikt** [comment]
@samdark Thank you for the clarification.

**Comment by pmjones** [comment]
To summarize:
1. It sounds like the root of the problem is in PHP 5.4, not in Aura\Intl per se. (Please correct me if I misunderstood this.)
2. Even so, it seems like it should be possible to come up with a workaround so that Aura\Intl can handle "select" on PHP 5.4.

Is that about right?

**Comment by samdark** [comment]
Yes. Workaround is the same for both 5.3 and 5.4.

**Comment by pmjones** [comment]
/me nods

The workaround, as far as you can tell, is "replacing named parameters with positional ones and adding dummy values for parameters where data wasn't provided" -- yes?  If so, I'll see what I can do; in the mean time, if you come up with something for Yii that can be used as an example, or ported, or otherwise shared, I'd be very interested to see it.  (If not, no big deal.)

Either way, thanks for taking the time to examine the codebase and report the problem!

**Comment by samdark** [comment]
Correct. That's what I have for Yii https://github.com/yiisoft/yii2/pull/917/files#diff-0968cc0757071ec901e4c4dfac1145cdR20 but it doesn't correctly handle this exact situation yet. Not going to work on it till later next week for sure.

**Comment by pmjones** [comment]
Very good. If I come up with anything I'll let you know.  Again, my thanks for your time and attention.

**Comment by samdark** [comment]
We've decided to implement ICU grammar parsing in Yii for this particular fix. Already passes tests we have. Mind if we'll borrow some tests of yours?

**Comment by pmjones** [comment]
Please, by all means.  It would be nice to see come credits in the comments.

**Comment by harikt** [comment]
:+1:

**Comment by harikt** [comment]
@samdark did you fixed it in yii. If so can we borrow some code then . Or a PR to fix the issue is welcome.

Thanks

**Comment by samdark** [comment]
Yes, it's fixed in https://github.com/yiisoft/yii2/. I don't think I'll have enough time do a pull request. We're preparing beta.

**Comment by pmjones** [comment]
If you might point us to the right section(s) of the codebase, we can review on our own.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/i18n/MessageFormatter.php

**Comment by harikt** [comment]
@pmjones it seems we need to use this method https://github.com/yiisoft/yii2/blob/master/framework/i18n/MessageFormatter.php#L95-L99

**Comment by harikt** [comment]
Thank you @samdark for pointing to it.

**Comment by pmjones** [comment]
Since PHP 5.3 is now end-of-life and PHP 5.4 is nearing it, I'm OK with making this a documentation fix. something along the lines of "PHP 5.4.x and previous do not do this correctly."
